{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if and .Values.prometheus.enabled .Values.prometheus.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    app.kubernetes.io/component: prometheus
    self-monitor: {{ .Values.prometheus.serviceMonitor.selfMonitor | quote }}
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    {{- with .Values.prometheus.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.prometheus.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.prometheus.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if .Values.prometheus.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.prometheus.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.prometheus.service.ipDualStack.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.prometheus.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.prometheus.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.prometheus.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if ne .Values.prometheus.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.prometheus.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: {{ .Values.prometheus.prometheusSpec.portName }}
      protocol: TCP
      {{- if eq .Values.prometheus.service.type "NodePort" }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      {{- end }}
      port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
    - name: reloader-web
      protocol: TCP
      {{- if semverCompare "> 1.20.0-0" $kubeTargetVersion }}
      appProtocol: http
      {{- end }}
      port: {{ .Values.prometheus.service.reloaderWebPort }}
      targetPort: reloader-web
    {{- if .Values.prometheus.thanosIngress.enabled }}
    - name: grpc
      protocol: TCP
      {{- if eq .Values.prometheus.service.type "NodePort" }}
      nodePort: {{ .Values.prometheus.thanosIngress.nodePort }}
      {{- end }}
      port: {{ .Values.prometheus.thanosIngress.servicePort }}
      targetPort: {{ .Values.prometheus.thanosIngress.servicePort }}
    {{- end }}
    {{- with .Values.prometheus.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  publishNotReadyAddresses: {{ .Values.prometheus.service.publishNotReadyAddresses }}
  selector:
    {{- if .Values.prometheus.agentMode }}
    app.kubernetes.io/name: prometheus-agent
    {{- else }}
    app.kubernetes.io/name: prometheus
    {{- end }}
    operator.prometheus.io/name: {{ template "kube-prometheus-stack.prometheus.crname" . }}
    {{- with .Values.prometheus.prometheusSpec.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.prometheus.service.sessionAffinity }}
  sessionAffinity: {{ .Values.prometheus.service.sessionAffinity }}
  {{- end }}
  {{- if eq .Values.prometheus.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.prometheus.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
  type: {{ .Values.prometheus.service.type | quote }}
{{- end }}
